### ISSUE TITLE
Avoid the use of "var"

### ISSUE THREAD

**Issue by gargakshit** [KingConverter/KingConverter#17]
I noticed that you extensively use "var". Using var is not a good practice in modern JS due to scope leaking. Please try to use "let" and "const" wherever possible

**Comment by radiantly** [comment]
Thanks for pointing this out, we'll fix this as soon as possible!

**Comment by rohitsanj** [comment]
Thanks for pointing this out @gargakshit! We are looking to improve our code quality. Please feel free to raise any more issues! :)

**Comment by gargakshit** [comment]
Awesome
